---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: windows10
    driver:
      box: gusztavvargadr/w10e
  - name: windows16
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: 14x
    run_list:
      - recipe[gusztavvargadr_sql::2014_express]
  - name: 14d
    run_list:
      - recipe[gusztavvargadr_sql::2014_developer]
    attributes:
      gusztavvargadr_sql:
        2014_developer:
          installer_file_url: <%= ENV['gusztavvargadr_sql_2014_developer_installer_file_url'] %>
