---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: win10
    driver:
      box: gusztavvargadr/windows10ee
  - name: win12
    driver:
      box: gusztavvargadr/windows2012r2se

suites:
  - name: 14x
    run_list:
      - recipe[gusztavvargadr_sql::2014_express]
  - name: 14d
    run_list:
      - recipe[gusztavvargadr_sql::2014_developer]
    attributes:
      gusztavvargadr_sql:
        2014_developer:
          installer_file_url: <%= ENV['gusztavvargadr_sql_2014_developer_installer_file_url'] %>
