---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: windows10
    driver:
      box: gusztavvargadr/w10e
  - name: windows16
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: profiles
    run_list:
      - recipe[gusztavvargadr_svn::profiles]
    attributes:
      gusztavvargadr_svn:
        profiles:
          http://svn.apache.org/repos:
            checkout_directory_path: /Users/vagrant/Repos
            repositories:
              asf/logging/log4net/trunk:
