---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: win10
    driver:
      box: gusztavvargadr/windows10ee

suites:
  - name: 10p
    run_list:
      - recipe[gusztavvargadr_visual_studio::2010_professional]
  - name: 15c
    run_list:
      - recipe[gusztavvargadr_visual_studio::2015_community]
  - name: 15p
    run_list:
      - recipe[gusztavvargadr_visual_studio::2015_professional]
