---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: windows10
    driver:
      box: gusztavvargadr/w10e
  - name: windows16
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: 10p
    run_list:
      - recipe[gusztavvargadr_visual_studio::2010_professional]
  - name: 15c
    run_list:
      - recipe[gusztavvargadr_visual_studio::2015_community]
  - name: 15p
    run_list:
      - recipe[gusztavvargadr_visual_studio::2015_professional]
