---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: win12
    driver:
      box: gusztavvargadr/windows2012r2se

suites:
  - name: default
    run_list:
      - recipe[gusztavvargadr_iis::default]
