---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant
  provider: <%= ENV['VAGRANT_PREFERRED_PROVIDERS'] || ENV['VAGRANT_DEFAULT_PROVIDER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: w
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s

suites:
  # - name: 14x
  #   run_list:
  #     - recipe[gusztavvargadr_windows::updates]
  #     - recipe[gusztavvargadr_sql::2014_requirements]
  #     - recipe[gusztavvargadr_sql::2014_express]
  # - name: 14d
  #   run_list:
  #     - recipe[gusztavvargadr_windows::updates]
  #     - recipe[gusztavvargadr_sql::2014_requirements]
  #     - recipe[gusztavvargadr_sql::2014_developer]
  - name: 2017-developer
    run_list:
      - recipe[gusztavvargadr_mssql_test::2017_developer]
  - name: 2017-ssms
    run_list:
      - recipe[gusztavvargadr_mssql_test::2017_ssms]
