---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant
  provider: <%= ENV['VAGRANT_PREFERRED_PROVIDERS'] || ENV['VAGRANT_DEFAULT_PROVIDER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: gusztavvargadr/w16s-de
  - name: u16s
    transport:
      name: ssh
    driver:
      box: gusztavvargadr/u16s-dc

suites:
  - name: images
    run_list:
      - recipe[gusztavvargadr_docker_test::images]
    attributes:
      gusztavvargadr_docker:
        images:
          hello-world:
