driver:
  name: vagrant
  vagrantfiles:
    - ../../../src/kitchen.vagrant
  provider: <%= ENV['VAGRANT_PREFERRED_PROVIDERS'] || ENV['VAGRANT_DEFAULT_PROVIDER'] %>

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: w10
    transport:
      name: winrm
    driver:
      box: <%= ENV['VAGRANT_BOX_WINDOWS_DESKTOP'] || 'gusztavvargadr/w10e-dc' %>

suites:
  - name: 17c
    run_list:
      - recipe[gusztavvargadr_visualstudio_test::2017_community]
  - name: 17p
    run_list:
      - recipe[gusztavvargadr_visualstudio_test::2017_professional]
