---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: win10
    driver:
      box: gusztavvargadr/windows10ee

suites:
  - name: features
    run_list:
      - recipe[gusztavvargadr_windows::features]
    attributes:
      gusztavvargadr_windows:
        features:
          - TelnetClient
  - name: packages
    run_list:
      - recipe[gusztavvargadr_windows::packages]
    attributes:
      gusztavvargadr_windows:
        packages:
          Redgate DLM Automation Suite:
            source: https://download.red-gate.com/DLMAutomationSuite.exe
            options: /IAgreeToTheEULA /q
  - name: chocolatey_packages
    run_list:
      - recipe[gusztavvargadr_windows::chocolatey_packages]
    attributes:
      gusztavvargadr_windows:
        chocolatey_packages:
          nuget.commandline:
          git:
            version: 2.10.2
            options: -params '"/GitAndUnixToolsOnPath"'
