---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: windows16
    driver:
      box: gusztavvargadr/w16s

suites:
  - name: profiles
    run_list:
      - recipe[gusztavvargadr_windows::chocolatey_packages]    
      - recipe[gusztavvargadr_git::profiles]
    attributes:
      gusztavvargadr_windows:
        chocolatey_packages:
          git:
            version: '2.11.1.20170208'
            options: >-
              -params '"/GitAndUnixToolsOnPath"'
      gusztavvargadr_git:
        profiles:
          https://github.com:
            checkout_directory_path: /Users/vagrant/Repos
            repositories:
              github/gitignore:
          https://github.com/gusztavvargadr:
            username: <%= ENV['GIT_GITHUB_USERNAME'] %>
            password: <%= ENV['GIT_GITHUB_PASSWORD'] %>
            checkout_directory_path: /Users/vagrant/Repos/gusztavvargadr
            repositories:
              home:
