---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_solo

platforms:
  - name: win10
    driver:
      box: gusztavvargadr/windows10ee

suites:
  - name: profiles
    run_list:
      - recipe[gusztavvargadr_git::profiles]
    attributes:
      gusztavvargadr_git:
        profiles:
          https://github.com:
            checkout_directory_path: /Users/vagrant/Repos
            repositories:
              github/gitignore:
          https://github.com/gusztavvargadr:
            username: <%= ENV['GIT_GITHUB_USERNAME'] %>
            password: <%= ENV['GIT_GITHUB_PASSWORD'] %>
            checkout_directory_path: /Users/vagrant/Repos/gusztavvargadr
            repositories:
              home:
