---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2

provisioner:
  name: chef_solo

platforms:
  - name: windows16
    driver:
      box: gusztavvargadr/w16s-sql14d
      synced_folders:
        - ["data", "C:/vagrant-data"]

suites:
  - name: server-install
    run_list:
      - recipe[gusztavvargadr_octopus::server]
  - name: server-configure
    run_list:
      - recipe[gusztavvargadr_octopus::server]
    attributes:
      gusztavvargadr_octopus:
        server:
          web_username: vagrant
          web_password: Vagrant42
  - name: server-import
    run_list:
      - recipe[gusztavvargadr_octopus::server]
    attributes:
      gusztavvargadr_octopus:
        server:
          web_username: vagrant
          web_password: Vagrant42
          import:
            C:\\vagrant-data\\server\\import1: Vagrant42
            C:\\vagrant-data\\server\\import2: Vagrant42
  - name: tentacle-install
    run_list:
      - recipe[gusztavvargadr_octopus::tentacle]
  - name: tentacle-configure
    run_list:
      - recipe[gusztavvargadr_octopus::server]
      - recipe[gusztavvargadr_octopus::tentacle]
    attributes:
      gusztavvargadr_octopus:
        server:
          web_username: vagrant
          web_password: Vagrant42
          import:
            C:\\vagrant-data\\server\\import1: Vagrant42
            C:\\vagrant-data\\server\\import2: Vagrant42
        tentacle:
          server_web_username: vagrant
          server_web_password: Vagrant42
          environment_names:
            - environment1
            - environment2
          tenant_names:
            - tenant1
            - tenant2
          role_names:
            - role1
            - role2
